import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create role supabase_auth_admin;
create schema auth;create schema storage;create publication supabase_realtime;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}',encrypted_password text);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated,service_role;
grant all on storage.objects to authenticated;`);
const sql=readFileSync(new URL('../supabase/setup_all.sql',import.meta.url),'utf8').replaceAll('create extension if not exists pgcrypto;','');
await db.exec(sql);
await db.exec(readFileSync(new URL('../supabase/migrations/20261010_integrity_access.sql',import.meta.url),'utf8'));

const setter='33333333-3333-4333-8333-333333333333',sales='55555555-5555-4555-8555-555555555555';
await db.exec(`insert into public.reps(id,name,role) values('${setter}','Setter','appointment_setter'),('${sales}','Sales','salesperson');select set_config('request.jwt.claim.role','service_role',false);`);
const base={first_name:'Alex',last_name:'Morgan',phone:'7405550199',email:'alex@example.com',address:'18 Public Square.',city:'Mount Vernon',state:'OH',zip:'43050',homeowner_confirmed:false,consent_contact:true,source:'public_homeowner_form',notes:'Request',preferred_date:'2026-10-12',preferred_time_window:'Morning',scheduled_at:'2026-10-12T13:00:00Z',stage:'Confirmed',lead_id:'victim'};
async function save(input){return (await db.query('select public.atomic_save_homeowner_profile($1::jsonb) as result',[JSON.stringify(input)])).rows[0].result;}
const first=await save(base);assert.ok(first.ok);assert.notEqual(first.lead_id,'victim');
assert.equal((await db.query('select stage from public.appointments where id=$1',[first.appointment_id])).rows[0].stage,'Requested');
const second=await save(base);assert.notEqual(second.lead_id,first.lead_id);
const staff={...base,source:'appointment_setter',actor_id:setter,salesperson_id:sales,lead_id:first.lead_id,stage:'Confirmed',notes:'Staff update'};
const updated=await save(staff);assert.equal(updated.lead_id,first.lead_id);assert.equal(updated.updated,true);assert.equal(updated.appointment_id,first.appointment_id);
const matched=await save({...staff,lead_id:'',address:'18 Public Square',notes:'Matched punctuation'});assert.equal(matched.lead_id,first.lead_id);
const before=await db.query('select (select count(*) from leads) leads,(select count(*) from homeowner_intakes) intakes,(select count(*) from appointments) appointments');
await assert.rejects(save({...staff,lead_id:'',address:'99 Other St',salesperson_id:setter}),/salesperson/i);
const after=await db.query('select (select count(*) from leads) leads,(select count(*) from homeowner_intakes) intakes,(select count(*) from appointments) appointments');assert.deepEqual(after.rows,before.rows);
assert.equal((await db.query('select metadata from lead_activity where lead_id=$1 order by created_at desc limit 1',[first.lead_id])).rows[0].metadata.to_status,'Appointment');
console.log('Independent atomic SQL passed: public append-only Requested, staff existing update, normalized contact matching, invalid salesperson no partial writes, activity status');
await db.exec(`create function public.test_reject_appointment() returns trigger language plpgsql as $$begin if new.notes='FAIL_AFTER_INTAKE' then raise exception 'Forced late failure'; end if;return new;end $$;create trigger test_reject_appointment before insert on public.appointments for each row execute function public.test_reject_appointment();`);
await assert.rejects(save({...base,address:'99 Rollback St',notes:'FAIL_AFTER_INTAKE'}),/Forced late failure/);
const rolledBack=await db.query('select (select count(*) from leads) leads,(select count(*) from homeowner_intakes) intakes,(select count(*) from appointments) appointments');assert.deepEqual(rolledBack.rows,after.rows);
console.log('Independent late appointment failure rolled back prior lead/intake inserts');
await db.close();
