import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create role supabase_auth_admin;
create schema auth;create schema storage;create publication supabase_realtime;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}',encrypted_password text);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated,service_role;
grant all on storage.objects to authenticated;`);
const sql=readFileSync(new URL('../supabase/setup_all.sql',import.meta.url),'utf8').replaceAll('create extension if not exists pgcrypto;','');
await db.exec(sql).catch(e=>{console.error(e.message);process.exit(1)});
await db.exec(sql).catch(e=>{console.error(e.message);process.exit(1)});
console.log('Full fresh schema and repeat setup executed');
await db.close();
