import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');
const code=source.slice(source.indexOf('function routeBuildKey(){'),source.indexOf('async function fetchRoadRoute('));
const badge=source.slice(source.indexOf('function updateSelectedBadge(){'),source.indexOf('function readRouteTrayCollapsed('));
const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{value:id==='routeCount'?'25':'',textContent:'',disabled:false});return elements.get(id)};
let requests=0,release;
const state={routeMode:'driving',selected:new Set(['a']),leads:[{id:'a',lat:40,lng:-82},{id:'b',lat:41,lng:-82}],routeStops:[],map:null};
const context=vm.createContext({state,$,window:{},openRoutePanel(){},isCoords:()=>true,alert(){},nearestNeighbor2Opt:rows=>rows,renderRouteStops(){},endNavigation(){},fetchRoadRoute:async()=>{requests++;await new Promise(resolve=>{release=resolve})},updateRouteTraySummary(){},shouldExpandRouteTray:()=>false,liftMapChrome(){}});
vm.runInContext(code+badge,context);
const build=context.optimizeAndDrawRoute();assert.equal(requests,1);
assert.equal($('routeTray').dataset.routeBuilding,'true');assert.equal($('routeTray').dataset.routeReady,'false');
await context.optimizeAndDrawRoute();assert.equal(requests,1,'double click cannot duplicate upstream routing');
assert.equal(state.routeStops[0].id,'a');release();await build;
assert.equal($('routeTray').dataset.routeReady,'true');assert.equal($('routeTray').dataset.routeStopCount,'1');
state.selected=new Set(['b']);context.updateSelectedBadge();assert.equal(state.routeStops.length,0,'same-sized selection change invalidates built route');assert.equal($('routeTray').dataset.routeReady,'false');
const second=context.optimizeAndDrawRoute();assert.equal(state.routeStops[0].id,'b');release();await second;
$('routeCount').value='10';context.updateSelectedBadge();assert.equal(state.routeStops.length,0,'max-stop changes invalidate built route');
state.selected.clear();await context.optimizeAndDrawRoute();assert.equal(requests,2,'empty selection cannot request route');
console.log('Actual route building, duplicate-click guards and stale-selection invalidation passed.');
