import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create role supabase_auth_admin;
create schema auth;create schema storage;create publication supabase_realtime;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}',encrypted_password text);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated,service_role;
grant all on storage.objects to authenticated;`);
const sql=readFileSync(new URL('../supabase/setup_all.sql',import.meta.url),'utf8').replaceAll('create extension if not exists pgcrypto;','');
await db.exec(sql);
await db.exec(readFileSync(new URL('../supabase/migrations/20261010_integrity_access.sql',import.meta.url),'utf8'));

const admin='11111111-1111-4111-8111-111111111111',uid='22222222-2222-4222-8222-222222222222',member='33333333-3333-4333-8333-333333333333',inactive='44444444-4444-4444-8444-444444444444',form='55555555-5555-4555-8555-555555555555',item='66666666-6666-4666-8666-666666666666';
await db.exec(`insert into auth.users(id,email,encrypted_password) values('${uid}','test@example.com','old');insert into reps(id,user_id,name,role) values('${admin}','${uid}','Test Admin','admin');insert into reps(id,name,role,active) values('${member}','Member','salesperson',true),('${inactive}','Inactive','salesperson',false);insert into form_templates(id,name,audience) values('${form}','Test Form','both');insert into leads(id,source,address,name,city,state,zip) values('TEST','Synthetic','Synthetic','Test','Test','OH','43050');select set_config('request.jwt.claim.sub','${uid}',false);select set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);
await db.query('select replace_form_assignments($1,$2::uuid[])',[form,[member]]);
await assert.rejects(db.query('select replace_form_assignments($1,$2::uuid[])',[form,[inactive]]),/active team/i);
assert.equal((await db.query('select rep_id from form_assignments where template_id=$1',[form])).rows[0].rep_id,member);
await db.query('select save_training_item($1::jsonb,$2::uuid[])',[JSON.stringify({id:item,title:'Initial',kind:'image',storage_path:'test.png'}),[member]]);
await assert.rejects(db.query('select save_training_item($1::jsonb,$2::uuid[])',[JSON.stringify({id:item,title:'Bad update',kind:'image'}),[inactive]]),/active team/i);
assert.equal((await db.query('select title from training_items where id=$1',[item])).rows[0].title,'Initial');
await db.exec(`reset role;update reps set must_change_password=true where id='${admin}';set role authenticated;`);
assert.equal((await db.query('select session_ready() ready')).rows[0].ready,false);
assert.equal((await db.query('select count(*)::int n from leads')).rows[0].n,0);
assert.equal((await db.query('select count(*)::int n from reps where id=$1',[admin])).rows[0].n,1,'Flagged user can read own profile');
await assert.rejects(db.query('select clear_must_change_password()'),/Change your password/);
await db.exec(`reset role;update auth.users set encrypted_password='new' where id='${uid}';set role authenticated;`);
await db.query('select clear_must_change_password()');
assert.equal((await db.query('select session_ready() ready')).rows[0].ready,true);
assert.equal((await db.query('select count(*)::int n from leads')).rows[0].n,1);
console.log('Inactive-assignee rejection preserves assignments/training; flagged operation denied; own recovery clears after actual Auth password change');
await db.close();
